In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data_billetes.csv')

In [3]:
data.head()

Image.Var  Image.Skew  Image.Curt  Entropy  Class
0    3.62160      8.6661     -2.8073 -0.44699      0
1    4.54590      8.1674     -2.4586 -1.46210      0
2    3.86600     -2.6383      1.9242  0.10645      0
3    3.45660      9.5228     -4.0112 -3.59440      0
4    0.32924     -4.4552      4.5718 -0.98880      0

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
#df_feat = pd.DataFrame(scaled_features , columns=data.columns[:-1])

df_feat = data.drop('Class' , axis=1)

In [6]:
df_feat.head()

Image.Var  Image.Skew  Image.Curt  Entropy
0    3.62160      8.6661     -2.8073 -0.44699
1    4.54590      8.1674     -2.4586 -1.46210
2    3.86600     -2.6383      1.9242  0.10645
3    3.45660      9.5228     -4.0112 -3.59440
4    0.32924     -4.4552      4.5718 -0.98880

In [7]:
# train test slipt
X = df_feat
y = data['Class']

In [8]:
from sklearn.cross_validation import train_test_split

C:\Users\miguel\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [9]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.3)

### MLPC Classifier

In [10]:
from sklearn.neural_network import MLPClassifier

In [34]:
X_train.head()

Image.Var  Image.Skew  Image.Curt   Entropy
1050    -5.8818      7.6584     0.55580 -2.915500
36       2.6881      6.0195    -0.46641 -0.692680
167      1.0235      6.9010    -2.00620 -2.712500
316      5.7353      5.2808    -2.25980  0.075416
1299    -1.0802      2.1996    -2.58620 -1.275900

In [36]:
y_train.head()

1050    1
36      0
167     0
316     0
1299    1
Name: Class, dtype: int64

In [35]:
X_train.shape

(960, 4)

In [16]:
clf = MLPClassifier(hidden_layer_sizes=(2,15,6,7,6) , solver='lbfgs' , epsilon=1e-3 ,
                   random_state = 1 , learning_rate_init = 0.3 , max_iter = 10,
                   momentum = 0.2)

In [17]:
clf.fit(X_train , y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=0.001,
       hidden_layer_sizes=(2, 15, 6, 7, 6), learning_rate='constant',
       learning_rate_init=0.3, max_iter=10, momentum=0.2,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

### Evaluacion del Modelo

In [18]:
note_predictions = clf.predict(X_test)

In [19]:
from sklearn.metrics import classification_report,confusion_matrix

In [20]:
print(confusion_matrix(y_test , note_predictions))

[[208  10]
 [ 18 176]]


In [21]:
print(classification_report(y_test , note_predictions))

             precision    recall  f1-score   support

          0       0.92      0.95      0.94       218
          1       0.95      0.91      0.93       194

avg / total       0.93      0.93      0.93       412



In [22]:
#Comparando con Random Forest

In [23]:
from sklearn.ensemble import RandomForestClassifier

C:\Users\miguel\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [24]:
rfc = RandomForestClassifier(n_estimators=50 , random_state= 454545)

In [25]:
rfc.fit(X_train , y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=454545, verbose=0,
            warm_start=False)

In [26]:
rfc_preds = rfc.predict(X_test)

In [27]:
print(classification_report(y_test , rfc_preds))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00       218
          1       0.99      1.00      1.00       194

avg / total       1.00      1.00      1.00       412



In [28]:
print(confusion_matrix(y_test , rfc_preds))

[[217   1]
 [  0 194]]


In [29]:
rfc.feature_importances_

array([0.55167728, 0.23730134, 0.15537762, 0.05564376])